### PR TITLE
Few things worth mentioning.

### PR DESCRIPTION
**Pull request by antihax**
I happened to notice you were using the library and there were a few things I would recommend changing in your code. Feel free to review or ignore if you wish.

Revisions below:
- Move pointers into contexts passed through request.Context().
- Replace TokenSource in session with text version of the Token.
- Add example handler to test token retention.
- Move multiple authenticators into one global passed through contexts.
- Change state from potentially leakable sessionID, to a random string.

### CODE REVIEW

**Comment by maurerit** [comment]
Excellent feedback and much appreciated, will review once I haven't been staring at code and my budget for hours on end, lol.

Still quite new to Golang so all the feedback I can get will be used ;).

**Comment by maurerit** [comment]
Yeah... brain exploded while reading the diff... will process when my brain isn't mush ;)

**Comment by antihax** [comment]
I am in #devfleet and #esi on tweetfleet slack if you ever need to chat.

**Comment by maurerit** [comment]
- Move pointers into contexts passed through request.Context().
  - I dig it, was wondering about how to achieve this in a sane manor in golang
- Replace TokenSource in session with text version of the Token.
  - Thanks, after committing this initial experiment I finally wrapped my brain around the terminology in the code and some of the facilities you make available in your library to store and reuse tokens, just didn't have the brain power to fully make the needed change that you provided.  This will come in extremely handy not here but in the auth-srv which will be the actual place where these tokens are stored.  Obviously this process will be what obtains the token and it will later be passed onto the auth-srv for storage.
- Add example handler to test token retention.
  - This will come in extremely handy at least for the rest of the processes planned in this full project.
- Move multiple authenticators into one global passed through contexts.
  - I was a bit conflicted about where this should live, while at first I didn't want to have to instantiate a new authenticator per request, the fact that the scopes live inside the authenticator made me go this route for future proofing.  I'm not entirely sure what all scopes I'll use atm and want each and every individual user able to select the scopes they want to authorize and don't want this to leak from session to session.
  - **I think maybe using this context mechanism through the middleware and instantiating a new authenticator only when new scopes are requested is the sanest route?**
- Change state from potentially leakable sessionID, to a random string.
  - This too I debated on, wasn't sure if there were any implications security wise.  Should have taken the safe route as you did ;).

**Comment by antihax** [comment]
On the authenticators, you can create an authenticator with as many scopes as you will possibly use and then only actually use the ones the user selects through `AuthorizeURL()`.

Here is how I am handling it. https://github.com/antihax/evedata/blob/master/views/authentication.go#L136

**Comment by maurerit** [comment]
AHA, THAT's the use of the scopes parameter on the AuthorizeURL.  I haven't had the time to dive into how you were using the authenticators scopes vs that parameter to fully understand what needed to do what where.  Thanks for the clarification.

**Pull request merged**
